{% set version = "0.8.4" %}

package:
  name: skrebate
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/skrebate/skrebate-{{ version }}.tar.gz
  sha256: 4b590dfbc64ab5f6d6b215a07a472a7e8f8990f395f37bde33fe171b852b449b

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - joblib
    - numpy
    - python >={{ python_min }}
    - scikit-learn
    - scipy

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - skrebate
    - skrebate.multisurf
    - skrebate.multisurfstar
    - skrebate.relieff
    - skrebate.scoring_utils
    - skrebate.surf
    - skrebate.surfstar
    - skrebate.turf
    - skrebate.vls
  commands:
    - pip check

about:
  home: https://epistasislab.github.io/scikit-rebate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    A scikit-learn-compatible Python implementation of ReBATE, a suite of
    Relief-based feature selection algorithms for Machine Learning.
  description: |
    These algorithms excel at identifying features that are predictive of the
    outcome in supervised learning problems, and are especially good at
    identifying feature interactions that are normally overlooked by standard
    feature selection methods.
  dev_url: https://github.com/EpistasisLab/scikit-rebate

extra:
  recipe-maintainers:
    - bollwyvl
    - lacava
    - rhiever
    - weixuanfu
