{% set name = "skrebate" %}
{% set version = "0.62" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b20dad4dc52f650e1f7960151314840f34251222cae0a78ac23d9f6d377ca558

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - numpy
    - python >=2.7
    - scikit-learn
    - scipy
    # undeclared dep, imported by skrebate.vlsrelief
    - pandas

test:
  requires:
    - pip
  imports:
    - skrebate
    - skrebate.multisurf
    - skrebate.multisurfstar
    - skrebate.relieff
    - skrebate.scoring_utils
    - skrebate.surf
    - skrebate.surfstar
    - skrebate.turf
    - skrebate.vlsrelief
  commands:
    - python -m pip check

about:
  home: https://epistasislab.github.io/scikit-rebate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    A scikit-learn-compatible Python implementation of ReBATE, a suite of
    Relief-based feature selection algorithms for Machine Learning.
  description: |
    These algorithms excel at identifying features that are predictive of the
    outcome in supervised learning problems, and are especially good at
    identifying feature interactions that are normally overlooked by standard
    feature selection methods.
  doc_url: https://epistasislab.github.io/scikit-rebate
  dev_url: https://github.com/EpistasisLab/scikit-rebate

extra:
  recipe-maintainers:
    - bollwyvl
    - lacava
    - rhiever
    - weixuanfu
