{% set name = "skrebate" %}
{% set version = "0.61" %}
{% set sha256 = "cb4441e6833ecf5e359f9e1048e78abf7859d8a5da249df6a7d1c80c3b99a5b4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - numpy
    - python
    - scikit-learn
    - scipy
    - pandas

test:
  imports:
    - skrebate
    - skrebate.multisurf
    - skrebate.multisurfstar
    - skrebate.relieff
    - skrebate.scoring_utils
    - skrebate.surf
    - skrebate.surfstar
    - skrebate.turf
    - skrebate.vlsrelief

about:
  home: https://epistasislab.github.io/scikit-rebate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    A scikit-learn-compatible Python implementation of ReBATE, a suite of
    Relief-based feature selection algorithms for Machine Learning.
  description: |
    These algorithms excel at identifying features that are predictive of the
    outcome in supervised learning problems, and are especially good at
    identifying feature interactions that are normally overlooked by standard
    feature selection methods.
  doc_url: https://epistasislab.github.io/scikit-rebate
  dev_url: https://github.com/EpistasisLab/scikit-rebate

extra:
  recipe-maintainers:
    - bollwyvl
    - lacava
    - rhiever
    - weixuanfu
