travis:
  secure:
    BINSTAR_TOKEN: Jjhc9+V+oIA7SnFzYEz0tP4I5+DQ6S9Nh/Fkb6uvaQfZdGEkAvKev21MbqLd61EEpz9F6C/nxbCepynir1hcV2DTjDDCCiX5fqOUIop89cRidA1eKp0MjHrJzbhDYf3DKmawZnd/meSVjyv9UsegZ5G87qFLCpeNFh9TWZ9J4JEoULjlWZAaCADuHcn1wOrmIDzVjUUA4g7nkni8cqaFI0UyucmH4aGe0y2zNdDumWCEG40hcvm638ooMIOD+PMbJrvJTNBBV+JILJ7fSpijZ90BvtODzuMrrlLgYUTUZL+iqO18Z2LPzXxNYSFruhIxvllOp2eKtEJQUzRA7rSDo1b3/cDCwSTyLiZ2emQqi8yQ9QCj2491PH5/mQcIff1t/efuTC7zXif5WDnK20/iSt549Uw1dw86rbyW5+IiTLWpLrs+3NSq/SLB6SrU2UBhhzKCSTUWoNo0niLGim6OeXOGwkjRpgRbg1hw6PGDHKP6URvt0JKWoCVj36aZj3hYJ4mZO2a05OlPSpJ5VA1XZae15GcMg6XDl3pZ1h/LGbdDz416E7vYkLwTC7j5n1AS5tebziZZoYGPmTzQzRDZo1bjuESkYQ303KINAskbsMKq/mE1oVfZoTHSykp9q3maMz5fmw5mS2hkfl2suPrS0cGLYk+Gn2kmmHma35sAmG4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
